spring.application.name=petcare-system-II
spring.datasource.url=jdbc:postgresql://localhost:5432/petcare_ii
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true